#!/bin/bash
# smoke-all-archs.sh — comprehensive coherence smoke across every Swift
# model architecture in `Libraries/MLXLLM/Models/` and `Libraries/MLXVLM/Models/`.
#
# One representative model per architecture (4-bit when available; bf16 fallback
# for arches without a public 4-bit MLX checkpoint). Each model is exercised
# under `--kv none`, `--kv affine4`, and `--kv turbo4` to verify the three
# canonical KV-compression paths produce coherent output end-to-end.
#
# Run overnight on first invocation — uncached models will trigger HF
# downloads (~125GB total across ~25 new architectures). Subsequent runs hit
# the local cache and complete in ~60-90 minutes wall time on M1 Max 64GB.
#
# Output:
#   benchmarks/smoke-all-archs-YYYY-MM-DD.log   (full bench output)
#   benchmarks/smoke-all-archs-YYYY-MM-DD.md    (pass/fail matrix + first ~120
#                                                chars of generated output for
#                                                coherence verification)
#
# Usage:
#   ./scripts/smoke-all-archs.sh           # full sweep (LLMs + VLMs)
#   ./scripts/smoke-all-archs.sh llms      # LLMs only
#   ./scripts/smoke-all-archs.sh vlms      # VLMs only
#
# Override the KV configs (default: none,affine4,turbo4):
#   SMOKE_KV=none ./scripts/smoke-all-archs.sh

set -uo pipefail

cd "$(dirname "$0")/.."

KV="${SMOKE_KV:-none,affine4,turbo4}"
DATE="$(date +%Y-%m-%d)"
LOG_LLM="benchmarks/smoke-all-archs-${DATE}.llm.log"
LOG_VLM="benchmarks/smoke-all-archs-${DATE}.vlm.log"
SUMMARY="benchmarks/smoke-all-archs-${DATE}.md"
mode="${1:-all}"

# ─── Architecture coverage ────────────────────────────────────────────────────
# One model per `Libraries/MLXLLM/Models/*.swift` and `Libraries/MLXVLM/Models/*.swift`
# architecture. Sizes biased to small/medium when available so the sweep stays
# under ~90 min on warm cache. Skipped: Bitnet (1.58-bit), DeepseekV3/V4 (>>64GB),
# MiniMax/MiniMaxM2 (456B+), Lille130m + NanoChat (toy), Gemma 1.x + Phi 1.x
# (superseded), AfMoE + Olmo3 (HF gated), BailingMoe (no 4bit, only 2bit DWQ).

LLMS="\
qwen35-0.8b,\
qwen35-35b-a3b,\
qwen36-27b,\
qwen25-7b,\
qwen3-4b,\
qwen3-30b-a3b,\
gpt-oss-20b,\
nemotron-30b-a3b,\
gemma4-e2b,\
lfm2-1.2b,\
lfm2.5-1.2b,\
ministral3-3b,\
gemma3-1b,\
glm4-9b,\
llama3.2-3b,\
phi3.5-mini,\
phi3.5-moe,\
olmo2-7b,\
olmoe-1b-7b,\
granite3.3-2b,\
granite4-h-tiny,\
falcon-h1-7b,\
jamba-reasoning-3b,\
smollm3-3b,\
mimo-7b,\
exaone4-1.2b,\
gemma2-2b,\
gemma3n-e2b-text,\
cohere-command-r,\
internlm2.5-7b,\
minicpm3-4b,\
apertus-8b,\
starcoder2-7b,\
baichuan-m1-14b,\
lfm2-8b-a1b,\
ernie4.5-21b-a3b,\
openelm-1.1b,\
mimov2-flash"
# Excluded from default sweep: glm4.5-air (110B/12B-A MoE — marginal on 64GB).
# Add explicitly with: SMOKE_KV=none ./scripts/smoke-all-archs.sh + edit LLMS.

VLMS="\
lfm2vl-1.6b,\
lfm2.5vl-1.6b,\
mistral3vl-24b,\
qwen2vl-2b,\
qwen25vl-3b,\
qwen3vl-4b,\
fastvlm-0.5b,\
gemma3-4b,\
glm-ocr,\
pixtral-12b,\
idefics3-8b,\
smolvlm-v1,\
smolvlm2-2.2b,\
mimovl-7b"

# ─── Run ─────────────────────────────────────────────────────────────────────

run_llms() {
    local llm_count=$(echo "$LLMS" | tr ',' '\n' | grep -c .)
    echo "[SMOKE] LLM sweep — $llm_count architectures × $(echo "$KV" | tr ',' '\n' | grep -c .) KV configs"
    echo "[SMOKE] Logging to: $LOG_LLM"
    ./scripts/benchmark.sh --model "$LLMS" --method simple --kv "$KV" 2>&1 | tee "$LOG_LLM"
}

run_vlms() {
    local vlm_count=$(echo "$VLMS" | tr ',' '\n' | grep -c .)
    echo "[SMOKE] VLM sweep — $vlm_count architectures × $(echo "$KV" | tr ',' '\n' | grep -c .) KV configs"
    echo "[SMOKE] Logging to: $LOG_VLM"
    ./scripts/benchmark.sh --model "$VLMS" --method vision --kv "$KV" 2>&1 | tee "$LOG_VLM"
}

# Markdown summary builder — pass/fail per cell + first chars of generated output.
build_summary() {
    {
        echo "# Architecture smoke matrix — $DATE"
        echo ""
        echo "Generated by \`scripts/smoke-all-archs.sh\` — one model per Swift"
        echo "architecture, exercised under each KV-compression scheme."
        echo ""
        for log in "$LOG_LLM" "$LOG_VLM"; do
            [ -f "$log" ] || continue
            echo ""
            if [[ "$log" == *.llm.log ]]; then
                echo "## LLM smoke (\`--method simple\`)"
            else
                echo "## VLM smoke (\`--method vision\`)"
            fi
            echo ""
            echo "| Model | KV | Result | Tok/s | First chars of output |"
            echo "|---|---|---|---|---|"
            # Re-parse bench log and emit one row per (model, kv).
            awk '
                /^\[INFO\] \[[0-9]+\/[0-9]+\] model=/ {
                    match($0, /model=([^ ]+) method=([^ ]+) quant=([^ ]+) kv=([^ ]+)/, arr)
                    cur_model = arr[1]; cur_kv = arr[4]
                    cur_output = ""; cur_tok = ""
                    cur_pass = 0
                }
                /^\[BENCH\] Output:/ {
                    sub(/^\[BENCH\] Output: /, ""); cur_output = substr($0, 1, 110)
                }
                /^\[BENCH\] Generation:/ {
                    sub(/^\[BENCH\] Generation: /, ""); cur_tok = $1 " " $2
                }
                /Test run with 1 test in 1 suite passed/ {
                    cur_pass = 1
                    gsub(/\|/, "\\|", cur_output)
                    print "| `" cur_model "` | " cur_kv " | ✅ PASS | " cur_tok " | " cur_output " |"
                }
                /^\[ERROR\] Run failed/ {
                    print "| `" cur_model "` | " cur_kv " | ❌ FAIL | — | (see log) |"
                }
            ' "$log"
        done
    } > "$SUMMARY"
    echo ""
    echo "[SMOKE] Summary written to: $SUMMARY"
}

case "$mode" in
    llms) run_llms ;;
    vlms) run_vlms ;;
    all)  run_llms; run_vlms ;;
    *)
        echo "Usage: $0 [all|llms|vlms]" >&2
        exit 2
        ;;
esac

build_summary
